### ISSUE TITLE
Dashboard Manager: Counters at the top display wrong count

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#117]
Counters of DTP, DUPs, studies, DOs, and People seem to be inaccurate (reported by @Gerd-ECRIN).

**Comment by cudillal** [comment]
Typo in code made it so that DUPs had the same counter as DTPs

**Comment by Gerd-ECRIN** [comment]
People is showing 17 although there are 16 in listing.

**Comment by cudillal** [comment]
Good catch, should be fixed now
