### ISSUE TITLE
Add push notifications after data upload to TSD

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#119]
Relevant users (user who uploaded, RM, and probably all the associated people in DTP that are users) should get a push notification after the successful upload of data to TSD

**Comment by cudillal** [comment]
Since notifications after data upload are not set up on TSD side yet, I manually sent 2 to your manager account @Gerd-ECRIN. I think you can just test that they appear once on your first login and do not appear again if you reload the page or re-login.
Also if you have an opinion on who should be informed of the data upload (see issue description above), please share it here or we can discuss it next Monday (we scheduled a meeting with Milen this Friday but he probably won't come, so by next Monday the relevant users to send the notifications to most likely won't have been set up on TSD's side).

**Comment by Gerd-ECRIN** [comment]
Message received. Group of informed people is fine.

**Comment by cudillal** [comment]
group of informed people agreed
