### ISSUE TITLE
DO details: can headers on modals be greyed out if no data?

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#14]
see below.
also: what are the 3 lines before the details?
to check also in study page.

![image](https://github.com/ecrin-github/rms-portal-new/assets/1004258/36109039-5247-4557-b528-5124d8b559d9)

**Comment by cudillal** [comment]
Also fixed for studies accordions

**Comment by sergiocontrino** [comment]
fixed
