### ISSUE TITLE
contact form not working

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#18]
error on sending

**Comment by sergiocontrino** [comment]
Failed to load resource:
https://api-v2.ecrin-rms.org/app/send-email
the server responded with a status of 404 ()

**Comment by Swarnalathaa** [comment]
with the new BE the fields for the contact form are subject, message, recipients, sender. But in the UI we have more fields than this. So a decision should be made about the required fields and for the instance i have not made any functionality integration for the contact form.
![Capture](https://github.com/ecrin-github/rms-portal-new/assets/34007219/485b05cc-4b65-46ad-8c74-b61d99fc60ae)
