### ISSUE TITLE
do object is attached to study, but i cannot access it from list

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#19]
https://crr.ecrin.org/studies/82e6926f-9aea-4333-a320-0876b07874ea/view

display do
https://crr.ecrin.org/data-objects/3550f52d-71cf-4381-81b0-b91ae3474f75/view

but from 
https://crr.ecrin.org/data-objects

i don't see it. also the search does not find it

**Comment by Swarnalathaa** [comment]
@sergiocontrino I am using the correct endpoint to fetch the data based on organisation. @iPr0ger can check from BE side to see whether the API is returning the correct results.

**Comment by sergiocontrino** [comment]
this does not seems to be valid any longer, closing.
