### ISSUE TITLE
parent study: drop down empty for user

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#23]
when adding a do, the parent study drop down is empty for a normal user (it works for manager)

see also #22

**Comment by cudillal** [comment]
@sergiocontrino please also tell me what fields of the parent study should appear where parent study is mentioned, fields currently used: displayTitle for DO view page, sdSid as main field in DO edit page dropdown and displayTitle as secondary field (smaller), and displayTitle in DO summary-page
