### ISSUE TITLE
Aside-internal component not collapsing and not showing all items instantly as Manager

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#24]
Left sidebar when logged in doesn't collapse/expand sometimes (button does nothing, neither does hovering out). Also, when logging in as manager, the sidebar only contains regular user items (dashboard, studies, DOs) and is missing manager items (DTP, DUP, People).

**Comment by sergiocontrino** [comment]
it seems fixed, closing.
