### ISSUE TITLE
we need script/api for manager to assign organisation to user.

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#25]
the manager is supposed to assign the organisation to the user. at the moment done directly in the db.
e.g.

```
update user_profiles set organisation_id='id_o'
where user_id='id_u';

```
or

```
update user_profiles set organisation_id= (select id from organisations where 
default_name=?) where user_id = (select id from users where email=?);

```

**Comment by cudillal** [comment]
@sergiocontrino It was actually already possible to edit the organisation of a user, I don't remember what was the thing about "people" that may not be actual users of the app, but at least for all users in the "users" table in the DB, we can assign them to an organisation.

**Comment by sergiocontrino** [comment]
the editing of the profile (adding superuser/organisation) works fine. nice!
