### ISSUE TITLE
Superuser in DB is not manager in the app

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#28]
The DB contains 2 different 'role' fields for a `User`: `isSuperUser` and `isStaff`, but both are required to be `True` for a `User` to be `Manager` on the app:
https://github.com/ecrin-github/rms-portal-new/blob/2b29c666224c03c4a4775585351e20ac8e622533/src/app/pages/internal/main-page/internal-main-page.component.ts#L59
https://github.com/ecrin-github/rms-portal-new/blob/2b29c666224c03c4a4775585351e20ac8e622533/src/app/pages/internal/main-page/internal-main-page.component.ts#L76

**Comment by cudillal** [comment]
I don't think there's anything to test, you can probably just close the issue @sergiocontrino

**Comment by sergiocontrino** [comment]
yes, remove any logic in the fe involving the staff is for the moment the right solution, closing.
