### ISSUE TITLE
Perform searches locally instead of querying the DB

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#29]
The search feature (in `summary-object.component.ts` for example) queries the DB, while the full list of items is already loaded. Instead, the filtering could be done locally on this full list of items, removing a DB query from the component processes, thus making the app faster.
Note: data updating on detached component re-attach (RouteReuseStrategy) uses the current search function with the DB query. This should be kept because the data may be modified in this case (thus requiring a DB query to get the updated data).

**Comment by cudillal** [comment]
I don't think the note is still relevant

**Comment by cudillal** [comment]
Note: not much to test, just check that searching works and that there is no loading animation (since no waiting for BE response)

**Comment by Gerd-ECRIN** [comment]
Looks good and seems to be fast (not enough items to have a stress test)
