### ISSUE TITLE
Get rid of the browser local storage for important info (user orgId, role, etc.)

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#32]
The browser's local storage is used to store sensitive info such as a user's orgId or role. This should be changed as this can be easily modified to gain unauthorized permissions in the app.

**Comment by cudillal** [comment]
This also fixed login page appearing for 1-2 seconds after logging in, before redirecting to internal main page

**Comment by sergiocontrino** [comment]
all seems fine, some bits of code need to be deleted at some point (either commented out now or unused at the moment).
