### ISSUE TITLE
browsing: we should allow pdf and json export (as in logged mode)

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#34]
at the moment the export buttons ofr pdf and json are hidden in browsing mode, but only editing should be banned.

**Comment by cudillal** [comment]
Fixed by this commit actually: [2170d8965c353455d5bd6c38dee1603823ccf982](https://github.com/ecrin-github/rms-portal-new/commit/2170d8965c353455d5bd6c38dee1603823ccf982)

**Comment by sergiocontrino** [comment]
done
