### ISSUE TITLE
upload button green (but not working) also when DTP not completed

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal-new#44]
i can see it as soon as i add a DO from the DTP set up tab.

note: my first attempt to add a study failed, then i added a DO successfully, then i was able to add study and the same object (that so appeared twice).

**Comment by cudillal** [comment]
@sergiocontrino shouldn't the buttons become green already after the "data agreement and preparation step" is completed?
![Screenshot 2024-05-30 at 10-51-45 ECRIN Clinical Research Data Sharing Repository](https://github.com/ecrin-github/rms-portal-new/assets/98537626/5eb68922-4226-4843-a001-0f03d5f53ead)

**Comment by cudillal** [comment]
Was just fixed in v1.0.1, needs testing

**Comment by cudillal** [comment]
Internal server error on TSD side for me too (I assume caused by the API change on our side to properly check for upload permissions), I wasn't able to organise a meeting with TSD to sort this out yet

**Comment by cudillal** [comment]
Fixed on 12/07

**Comment by sergiocontrino** [comment]
fixed, nice!
