### ISSUE TITLE
DUP: show access data for each associated DO

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#61]
In the "linked objects and people" tab, show under each associated DO the corresponding access data set in the "objects and access" tab of DTPs. Need to show access type + embargo date, which is a field to be added in the BE (and FE), probably replacing "embargo still applies" field (DTP to be modified in consequence). By default there should be no embargo date.
Edit: should probably also be displayed for DTPs?

**Comment by cudillal** [comment]
Displayed the data on both DTP and DUP pages

**Comment by Gerd-ECRIN** [comment]
Access Type and Embargo Date are displayed.

**Comment by cudillal** [comment]
@Gerd-ECRIN Do you have rights to close the issue now or still not?
