### ISSUE TITLE
DTP: rework data transfer process

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#64]
- "creation of DTP record": merge step with "Set up of user, objects, etc." + completion date
- "data & agreement preparation": remove "md access granted" field, DTA agreed date not null
- "quality checks of objects": invert the order with "transfer of objects to tsd", remove all fields except "qc checks completed"
- merge steps "transfer of objects to tsd" and "dtp completed, objects listed"
- remove change submission status (removing date values in fields should un-complete a step anyway)
--> associated DO upload button should be green and enabled after all steps (except last one) are completed

**Comment by Gerd-ECRIN** [comment]
Apply changes is missing on other tabs and is not fixed at the top like edit-button

**Comment by cudillal** [comment]
@Gerd-ECRIN data on other tabs have their own save/add buttons, but I can add it for consistency and to be able to save on other tabs after editing data on the first tab. Good catch on the not fixed issue, will fix as well.

**Comment by cudillal** [comment]
Actually, I noticed that for all individual pages (DTP, studies, DOs, etc.), headers are only fixed at the top when viewing (not when editing or adding). As the transition between not fixed and fixed is currently quite unsmooth, I opened an issue #100 and will make the headers fixed while editing and adding when this will be fixed.
