### ISSUE TITLE
Move "Object and Access" DTP tab to DO page

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#66]
The user adding the DO should also be setting the access data to it.
Currently there are duplicate fields between the DO and DTP pages (access type and details).
The access type should be mandatory.
The fields will also be changed, see #61

**Comment by cudillal** [comment]
Need confirmation on the fields kept (access type and embargo expiry date), here were the previous fields in the DTP tab: 
![image](https://github.com/ecrin-github/rms-portal-new/assets/98537626/7a794ca8-d1ff-495c-8a55-31a8e8891eb6)

**Comment by Gerd-ECRIN** [comment]
Access type and Embargo expiry date are now at DO level but for Controlled access type Details are missing.

**Comment by cudillal** [comment]
@Gerd-ECRIN I wonder if the pre-requisites tab in DTP, which is actually named "controlled access details" and is going to be moved at DO level (#102), covers the access type details, or if I should re-add a "access details" text field as before, what do you think?

**Comment by Gerd-ECRIN** [comment]
Pre-Requisite should go to DO in any case, but again, Pre-Requisite is a part from access level. See example at #67. For access type controlled there has to be an explaination field e.g. leading to organisations guideline.

**Comment by cudillal** [comment]
Added the details field back only for access type "controlled" (mandatory in that case)
