### ISSUE TITLE
DTP: Sort out the possible values for "access type" of DO in "Objects and access"

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#67]
![image](https://github.com/ecrin-github/rms-portal-new/assets/98537626/effa135b-b556-4cba-98ad-4dc9a8bcad64)

**Comment by Gerd-ECRIN** [comment]
In the case of DUP there are 3 (?) possibilities on-screen access, APP access and download. So with reducing this field to only public or restricted a second field is needed to automate the mentioned possibilities. Both public and restricted are controlled.
E.g. all researchers can download after ethics approval, all others have public on-screen access.

**Comment by cudillal** [comment]
@Gerd-ECRIN I'm adding this to the agenda for the next monday meeting
