### ISSUE TITLE
DTP: PDF export

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#68]
The PDF export would concern mostly the "set up" tab (in particular DOs). Details to be added later.

**Comment by sergiocontrino** [comment]
note: this will be useful because the exported pdf can be used as appendix to the DTA

**Comment by cudillal** [comment]
Will create another issue for DUP PDF export

**Comment by Gerd-ECRIN** [comment]
PDF is now ONLY Linked Objects and People tab. Likely insufficient. Should have at least a header "Data Transfer" with title and transfering Organisation.

**Comment by cudillal** [comment]
@Gerd-ECRIN I modified the title and added the transfering organisation field, this PDF is supposed to be used as appendix to the DTA, so I don't know if it needs more data than the linked objects and people tab, we can discuss that next Monday.

**Comment by Gerd-ECRIN** [comment]
Changed header looks fine now.

**Comment by sergiocontrino** [comment]
fine for this first version, possibly will revisit.
