### ISSUE TITLE
Study/DO summary pages: show all studies/DOs but ones from user org first

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#69]
When logged in, show all studies/DOs as in browsing mode on summary pages but with the studies/DOs from the user organisation first.

**Comment by cudillal** [comment]
Note: this would require displaying the organisation on the summary pages, and for that, one field would have to be removed (type or status).

**Comment by sergiocontrino** [comment]
we could also make the display more compact (in particular the actions icos could take less space)
