### ISSUE TITLE
DO: do something with the "managing organisation" field

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#77]
The field "managing organisation" of a DO is currently unused. It should be removed or used for something.

**Comment by sergiocontrino** [comment]
just remove from gui

**Comment by Gerd-ECRIN** [comment]
Still Repository organisation at Instance not used

**Comment by cudillal** [comment]
@Gerd-ECRIN this issue is for a different field that was called "managing organisation", at DO level

**Comment by Gerd-ECRIN** [comment]
This field should remain in the database but hidden in the form for later usage. It may be possible that a 3rd party is managing data sharing for several organisations.

**Comment by cudillal** [comment]
Ok, it is still there in the database but hidden from the form.

**Comment by sergiocontrino** [comment]
fixed, closing.
