### ISSUE TITLE
DUP: rework data use process (steps)

### ISSUE THREAD

**Issue by cudillal** [ecrin-github/rms-portal-new#95]
- merge step one and two with setup started and completed as fields for the merged step (like DTP)
- rename "availability confirmed" field to "availability expires"
- remove "access confirmed" field and merge last two steps
- rewrite stepper component to get rid of metronic library

**Comment by Gerd-ECRIN** [comment]
Availability expires is a future date? Please change

**Comment by cudillal** [comment]
Should be fixed now (forgot to mention the issue in the fixing commit)
