### ISSUE TITLE
Repository organisation at DO-Instance not used

### ISSUE THREAD

**Issue by Gerd-ECRIN** [ecrin-github/rms-portal-new#99]
The Repository organisation field at DO -> Instance level seems to be useless as a single Instance (data file) of a data object should belong to the organisation of that object. So organisation field on DO level should be sufficient.

**Comment by cudillal** [comment]
After discussion: rename the field to just "repository" or remove the field

**Comment by cudillal** [comment]
Modified to text field "repository", will be set automatically by TSD after uploading data (and can be set manually for other repositories)

**Comment by Gerd-ECRIN** [comment]
Fields are changed automatically after upload even when they are not empty.

**Comment by cudillal** [comment]
@Gerd-ECRIN We can probably assume the user entered the fields correctly before uploading to TSD, and in that case not overwrite for the non-empty fields.

**Comment by Gerd-ECRIN** [comment]
The question is, is the user expected to fill the fields? If yes, what content? If no, the fields should be inactive.
